export  const actions = {
    ADD_USER: "ADD_USER",
    INITIALIZE: "INITIALIZE",
    UPDATE_USER_INTRO: "UPDATE_USER_INTRO",
    UPDATE_USER_OVERALL_BASICS: "UPDATE_USER_OVERALL_BASICS",
    UPDATE_USER_OTHERS: "UPDATE_USER_OTHERS",
    CREATE_DATA : "CREATE_DATA"
};